services:
  sms2tg:
    build: .
    privileged: true
    restart: always
    devices:
    - /dev/ttyS0
    tty: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
