services:
  smsbox:
    build: .
    privileged: true
    restart: always
    devices:
      - /dev/ttyS0
    volumes:
      - .:/app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
